// Code generated by gen_token_parse.go; DO NOT EDIT.

package syntax

func (o *RedirOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *ProcOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *GlobOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *BinCmdOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *CaseOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *ParNamesOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *ParExpOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *UnAritOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *BinAritOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *UnTestOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

func (o *BinTestOperator) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }
