// Code generated by "stringer -type=ValueKind"; DO NOT EDIT.

package expand

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _ValueKind_name = "UnknownStringNameRefIndexedAssociativeKeepValue"

var _ValueKind_index = [...]uint8{0, 7, 13, 20, 27, 38, 47}

func (i ValueKind) String() string { _ = "STUB: not implemented"; return "" }
